# printWidth: 80
# tabWidth: 4
# useTabs: true
# semi: true
# singleQuote: false
# quoteProps: "as-needed"
# jsxSingleQuote: false
trailingComma: "all"
bracketSpacing: false
# bracketSameLine: false
# arrowParens: "always"
# rangeStart: 0
proseWrap: "preserve"
# htmlWhitespaceSensitivity: "css"
# vueIndentScriptAndStyle: false
# endOfLine: "lf"
# embeddedLanguageFormatting: "auto"
singleAttributePerLine: true
